### ISSUE TITLE
Parsing array of JSON

### ISSUE THREAD

**Issue by alakanaeru** [wlwtvr/log-to-json#3]
How to reproduce

```
#1 Copy the text below

display_data:{header:"header_1"  title:"title_2"}  display_data:{header:"header_2"  title:"title_2"}

#2 Then run

pbpaste | ./logtojson 

{
  "display_data": {
    "header": "header_2",
    "title": "title_2"
  }
}
```

Idk, but I expect that `display_data` is an array and it should be parsed as

```
"display_data": [
  {
    "header": "header_2",
    "title": "title_2"
  },
  {
    "header": "header_2",
    "title": "title_2"
  }
],
```

Wdyt?

**Comment by wlwtvr** [comment]
@alakanaeru i've made an improvements according to your reports in #1 and #3. would you mind reviewing my changes?

**Comment by alakanaeru** [comment]
> @alakanaeru i've made an improvements according to your reports in #1 and #3. would you mind reviewing my changes?

Ack. I've put some comments
